server:
  port: 18084

spring:
  application:
    name: nacos-config-example
  cloud:
    nacos:
      config:
        serverAddr: mse-dbefe434-p.nacos-ans.mse.aliyuncs.com
  config:
    import:
      - nacos:nacos-config-example.yml
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    com.alibaba.cloud.nacos.configdata: debug

